server:
  port: 10000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.40.229.92:3306/ad?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 3kiV34xHnzNF4TR.
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  resources:
    static-locations: classpath:/META-INF/resources/,\
      classpath:/resources/,classpath:/static/,classpath:/public/

file:
  url: http://file.moreeffect.cn/ad/
  image:
    path: /file/ad/





