server:
  port: 8090
  servlet:
    session:
      timeout: 86400s

spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
