server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.243.192:3306/ad?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 135246
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  resources:
    static-locations: classpath:/META-INF/resources/,\
      classpath:/resources/,classpath:/static/,classpath:/public/,file:${upload-image-path}
upload-image-path: /app/shandian/upload/




